### ISSUE TITLE
anti badword gak work

### ISSUE THREAD

**Issue by albertstyles312** [TobyG74/ElainaBOT#103]

**Comment by joe-arms** [comment]
Mute juga kayaknya 😅

**Comment by TobyG74** [comment]
untuk addbadword tambahin kata2 nya dulu, #addbadword _kata_

**Comment by TobyG74** [comment]
> Mute juga kayaknya 😅

Walaupun dimute atau banchat kalo kamu admin atau owner, bot nya akan tetep respon. mute = untuk grup, banchat = untuk semua chat

**Comment by joe-arms** [comment]
Gak auto kick klo ada yg ngucap badword yg dah ditambahin, 

Kalo aku sih gitu 😅

**Comment by TobyG74** [comment]
> Gak auto kick klo ada yg ngucap badword yg dah ditambahin,
> 
> Kalo aku sih gitu 😅

Diaktifin dulu

**Comment by albertstyles312** [comment]
> untuk addbadword tambahin kata2 nya dulu, #addbadword _kata_

udah add badword
dah coba badword di wa ke 2 ga kenapa napa

**Comment by albertstyles312** [comment]
![image](https://user-images.githubusercontent.com/72325255/103251299-f5151680-49aa-11eb-92ee-2f8c834f7dc6.png)
udah aktif pdhl
di group info juga aktif anti badword nya
