### ISSUE TITLE
play kok error gan? padahal udah pake api nya

### ISSUE THREAD

**Issue by ILHAMBISAMAR** [TobyG74/ElainaBOT#113]

**Comment by TobyG74** [comment]
Cek website api nya, jika sudah daftar pasti akan mendapat pesan masuk tentang api nya.

**Comment by ILHAMBISAMAR** [comment]
> Cek website api nya, jika sudah daftar pasti akan mendapat pesan masuk tentang api nya.

kalo stickernobg pake apikey vhtear ada sc nya ga gan?
