### ISSUE TITLE
KNP ANTI BADWORDNYA GAK BSA

### ISSUE THREAD

**Issue by A-N-O-N-Y-M-O-U** [TobyG74/ElainaBOT#117]

**Comment by TobyG74** [comment]
Ga bisa gmn?

**Comment by A-N-O-N-Y-M-O-U** [comment]
MASA ADA YG TOXIC GAK KE KICK

Pada tanggal Sel, 12 Jan 2021 12:44, TobyG74 <notifications@github.com>
menulis:
