### ISSUE TITLE
SCRIPTNYA TOLONG DI PERBAIKI NGAB MASA GW KEBANNED TRUS PADAHAL DAH PAKE WA MOD

### ISSUE THREAD

**Issue by A-N-O-N-Y-M-O-U** [TobyG74/ElainaBOT#127]

**Comment by HAFizh-15** [comment]
dek klo ga mau ke banned ya jangan nge bot lah gblk, semua ada resiko

**Comment by canzxmln** [comment]
lah ngamok klo gamau ke banned mah gausah nge bot malah nyalahin orang lagi lu. mending sono maen berby kalo mental ke banned malah nyalahin orang

**Comment by MrG3P5** [comment]
okaokawawo ngakak su

**Comment by HasamiAini** [comment]
**### to solve such problems ... just invite bots to the group ...
and don't use features often
broadcast
one of the reasons is often banned, used simultaneously
activate anti spam mode to avoid spam**
