### ISSUE TITLE
tetetetet

### ISSUE THREAD

**Issue by ILHAMBISAMAR** [TobyG74/ElainaBOT#134]

**Comment by MrG3P5** [comment]
udh install modulenya? dan runnya npm start?

**Comment by ILHAMBISAMAR** [comment]
> udh install modulenya? dan runnya npm start?

udah ngab, udah semuanya, tapi masih kyk gitu

**Comment by ILHAMBISAMAR** [comment]
> udh install modulenya? dan runnya npm start?

setelah install : npm install
terus ini pas install : npm install -g pm2

![IMG_20210129_205554_HHT](https://user-images.githubusercontent.com/73697931/106283760-e2755200-6274-11eb-8383-9c491408b0bd.jpg)

**Comment by nisxlinux** [comment]
nge runnya kok di vscode

**Comment by ILHAMBISAMAR** [comment]
> nge runnya kok di vscode

lebih bgusna di VSC bro, jadi gmpang klo nmbhin fitur
