### ISSUE TITLE
MagerNulis1 Err !

### ISSUE THREAD

**Issue by Renzie2161** [TobyG74/ElainaBOT#150]
Semua sudah saya lakukan mulai dari mendownload IMAGEMAGICK dan mencentang 1,2,3,5,6
Dan lain lain
tapi saat saya run commandnya seperti : #magernulis1 Saya Tampan
Tapi yang keluar malah kertas kosong bagaimana cara fix nya ?

**Comment by MFarelS** [comment]
Laptopga support imagemagick:v
