### ISSUE TITLE
Yang Eror

### ISSUE THREAD

**Issue by akujeleksad** [TobyG74/ElainaBOT#16]
#IG
#IGSTALK
#RESEP
#artinama

**Comment by TobyG74** [comment]
Udah masukin apikey blm? Apikey vhtear

**Comment by akujeleksad** [comment]
udh apikey barbar doang

**Comment by TobyG74** [comment]
Ya mana bisa bambang, apikeynya beda!

**Comment by idkmew** [comment]
> udh apikey barbar doang

apikey barbar ap ya?

**Comment by akujeleksad** [comment]
hmmmmmmmmm
