### ISSUE TITLE
Setup Prisma eror

### ISSUE THREAD

**Issue by dzyfar4** [TobyG74/ElainaBOT#168]
C:\ChisatoBOT>npx prisma db push
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path C:\Users\Administrator\AppData\Roaming\npm
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, lstat 'C:\Users\Administrator\AppData\Roaming\npm'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\Administrator\AppData\Local\npm-cache\_logs\2024-02-01T05_43_48_454Z-debug-0.log

**Comment by TobyG74** [comment]
Have u installed nodejs?
