### ISSUE TITLE
#quran

### ISSUE THREAD

**Issue by ghost** [TobyG74/ElainaBOT#20]
[EXEC] 29/11 14:50:59 #quran from undefined in BEE 𝐈 & ZEXX 𝐩 CHAL CGUB    G      NCY                  
index > [ERROR] ReferenceError: techidkey is not defined  
index >     at tobz (C:\ElainaBOT\tobz.js:1099:67)
index >     at runMicrotasks (<anonymous>)
index >     at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by TobyG74** [comment]
Join grup wa ajaa

**Comment by ghost** [comment]
Ok min
