### ISSUE TITLE
ASK

### ISSUE THREAD

**Issue by Pokoke-01** [TobyG74/ElainaBOT#4]
Apakah fitur text to sticker work?

**Comment by TobyG74** [comment]
Coba dulu, Jika masih Error nanti saya perbaiki

**Comment by Mrfky** [comment]
> Coba dulu, Jika masih Error nanti saya perbaiki

Bang ini make di termux bisa ga?

**Comment by TobyG74** [comment]
> > Coba dulu, Jika masih Error nanti saya perbaiki
> 
> Bang ini make di termux bisa ga?

Bisa asal udh install & pake ubuntu untuk penginstalan botnya

**Comment by Mrfky** [comment]
> > > Coba dulu, Jika masih Error nanti saya perbaiki
> > 
> > 
> > Bang ini make di termux bisa ga?
> 
> Bisa asal udh install & pake ubuntu untuk penginstalan botnya

Apa yang harus di install bang

**Comment by Pokoke-01** [comment]
> Coba dulu, Jika masih Error nanti saya perbaiki

Error bang, cuma ngirim text kosong gitu

**Comment by TobyG74** [comment]
Coba yang sekarang

**Comment by Pokoke-01** [comment]
> Coba yang sekarang

# Thanks bang!

Sekarang ttp dah bisa.

**Comment by heylooh** [comment]
> > > Coba dulu, Jika masih Error nanti saya perbaiki
> > 
> > 
> > Bang ini make di termux bisa ga?
> 
> Bisa asal udh install & pake ubuntu untuk penginstalan botnya

Install apa bang?
