### ISSUE TITLE
Sfire,Slighting,sandwriting error

### ISSUE THREAD

**Issue by MrPawNO** [TobyG74/ElainaBOT#44]
![Screenshot_1](https://user-images.githubusercontent.com/13583912/101589217-9519f880-3a1a-11eb-9750-ed6e78191cf7.png)

**Comment by TobyG74** [comment]
Udah di fix

**Comment by MrPawNO** [comment]
> Udah di fix

Di fix dari api nya?

Tapi tetep error di ane, pesan error nya sama kek gambar di atas

**Comment by TobyG74** [comment]
Isi apikey mu di fetcher.js & function.js

**Comment by MrPawNO** [comment]
> Isi apikey mu di fetcher.js & function.js

Udah ku isi di fetcher & function

tetep pesan error nya seperti diatas
