### ISSUE TITLE
kesalahan perintah #ttp, #simi 

### ISSUE THREAD

**Issue by DjKagetane** [TobyG74/ElainaBOT#57]
Galat di: https://api.areltiyan.site/sticker_maker?text=
Galat di: http://simsumi.herokuapp.com/api?text=

**Comment by TobyG74** [comment]
oke untuk ttp bakal w ganti api, untuk simsimi nanti bakal fix kembali jika udh 1 - 3 hari

**Comment by TobyG74** [comment]
udh w ganti, tinggal cek aja
