### ISSUE TITLE
ASK

### ISSUE THREAD

**Issue by Pokoke-01** [TobyG74/ElainaBOT#7]
#bugreport error 
-----
Bagaimana mengatasinya?
Laporan tidak terkirim ke owner,
Di terminal tertulis not a contact, padahal no owner sudah ada di  kontak.

**Comment by TobyG74** [comment]
Nulis nya bener ga? 6281311850715@c.us -> harus ada @c.us

**Comment by Pokoke-01** [comment]
> Nulis nya bener ga? [6281311850715@c.us](mailto:6281311850715@c.us) -> harus ada @c.us

Ok thanks, fixed.
