### ISSUE TITLE
MAGERNULIS ERROR

### ISSUE THREAD

**Issue by akujeleksad** [TobyG74/ElainaBOT#76]
eror ngab

**Comment by MFarelS** [comment]
> eror ngab

Udah Install ImageMagick ngab?

**Comment by MFarelS** [comment]
Waktu Install Centang Kolom 1,2,3,5,6

**Comment by akujeleksad** [comment]
download dimana

**Comment by akujeleksad** [comment]
kalo udah download clone dimana

**Comment by akujeleksad** [comment]
ga ada centangannya :v

**Comment by MFarelS** [comment]
Give Me RDP To Fix This awokwaokwaowooa
