### ISSUE TITLE
kokgini 

### ISSUE THREAD

**Issue by akujeleksad** [TobyG74/ElainaBOT#80]
(node:22368) UnhandledPromiseRejectionWarning: ReferenceError: prefix is not defined
    at tobz (C:\ElainaBOT-main\tobz.js:3640:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by akujeleksad** [comment]
Bantu napa!

**Comment by fairyenzy** [comment]
Sama saya juga gitu

**Comment by akujeleksad** [comment]
tunggu owner respon

**Comment by TobyG74** [comment]
https://github.com/TobyG74/ElainaBOT/blob/main/tobz.js#L131
