### ISSUE TITLE
woy Elaina bantu napa :(

### ISSUE THREAD

**Issue by akujeleksad** [TobyG74/ElainaBOT#81]
(node:34404) UnhandledPromiseRejectionWarning: ReferenceError: prefix is not defined
    at tobz (C:\ElainaBOT-main\tobz.js:3658:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:34404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)

**Comment by TobyG74** [comment]
tambahin prefix di setting

**Comment by akujeleksad** [comment]
udah w tambahin # tetep su

**Comment by TobyG74** [comment]
https://github.com/TobyG74/ElainaBOT/blob/main/tobz.js#L131

**Comment by akujeleksad** [comment]
oke thanks sayang
