### ISSUE TITLE
Help gua bang

### ISSUE THREAD

**Issue by akujeleksad** [TobyG74/ElainaBOT#87]
> ELAINABOT@3.0.0 start C:\ElainaBOT-main
> node index.js

Unable to load the sleep module (no animations available)
undefined:1

SyntaxError: Unexpected token
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ELAINABOT@3.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ELAINABOT@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Asus\AppData\Roaming\npm-cache\_logs\2020-12-17T09_38_48_496Z-debug.log

NOTE : gw ga otak atik

**Comment by akujeleksad** [comment]
bantu dong ;"(
**sad**

**Comment by TobyG74** [comment]
Lah lu abis install apaan? Yang lain ga error tuh
